channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _mutex_mxnet=0.0.50=openblas
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aom=3.5.0=h27087fc_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.2.0=py38h06a4308_0
  - blas=1.0=openblas
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py38h6a678d5_8
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - cffi=1.17.1=py38h1fdaa30_0
  - cryptography=43.0.0=py38hdda0065_0
  - cuda-cccl=12.4.127=0
  - cuda-command-line-tools=12.1.1=0
  - cuda-compiler=12.6.2=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cudart-static=12.1.105=0
  - cuda-cuobjdump=12.4.127=0
  - cuda-cupti=12.1.105=0
  - cuda-cupti-static=12.1.105=0
  - cuda-cuxxfilt=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.4.127=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.6.0=0
  - cuda-libraries-static=12.1.0=0
  - cuda-nsight=12.4.127=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=12.4.127=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvrtc-static=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=12.0.1=0
  - cuda-tools=12.1.1=0
  - cuda-visual-tools=12.6.0=0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.9.2.26=cuda11_0
  - cupti=11.3.1=0
  - dbus=1.13.18=hb2f20db_0
  - easydict=1.13=pyhff2d567_1
  - efficientnet-pytorch=0.7.1=pyhd8ed1ab_1
  - einops=0.8.0=pyhd8ed1ab_0
  - expat=2.6.4=h6a678d5_0
  - fastcache=1.1.0=py38h7b6447c_0
  - ffmpeg=4.4.2=gpl_h8dda1f0_112
  - fftw=3.3.10=nompi_hf0379b8_106
  - filelock=3.16.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.1=pyhe1237c8_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.10.0=pyhff2d567_0
  - ftfy=6.2.3=pyhd8ed1ab_0
  - future=0.18.3=py38h06a4308_0
  - gds-tools=1.9.1.3=0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.39=h4bc722e_0
  - harfbuzz=5.3.0=h418a68e_0
  - hdf5=1.12.2=nompi_h4df4325_101
  - hydra=2.5=py38h497a2fe_1
  - icu=70.1=h27087fc_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jinja2=3.1.4=py38h06a4308_0
  - joblib=1.4.2=py38h06a4308_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.3=h6a678d5_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcublas-static=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcufft-static=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcufile-static=1.9.1.3=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurand-static=10.3.5.147=0
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusolver-static=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libcusparse-static=12.0.2.55=0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.14=h166bdaf_0
  - libdrm=2.4.122=h4ab18f5_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=12.2.0=h65d4601_19
  - libgpg-error=1.51=h5eee18b_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libllvm15=15.0.7=hadd5161_1
  - libmxnet=1.9.1=openblas_h8848447_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnpp-static=12.0.2.50=0
  - libnvfatbin=12.4.127=0
  - libnvfatbin-dev=12.4.127=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libnvjpeg-static=12.1.1.14=0
  - libnvvm-samples=12.1.105=0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.21=h043d6bf_0
  - libopencv=4.6.0=py38h3504efa_3
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=15.2=hb675445_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=252=h2a991cd_0
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.4.0=h82bc61c_5
  - libtool=2.4.7=h6a678d5_0
  - libudev1=253=h0b41bf4_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.11.0=h295c915_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h166bdaf_4
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.7.0=h8db6258_0
  - mkl=2022.1.0=hc2b9512_224
  - mkl-service=2.4.0=py38h80f09db_0
  - mkl_fft=1.3.1=py38hf8530d2_4
  - mkl_random=1.2.2=py38h5ca245f_1
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=py38h06a4308_0
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.1=py38h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nsight-compute=2024.1.1.4=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - opencv=4.6.0=py38h578d9bd_3
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.0.15=h5eee18b_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.42=hebb0a14_1
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py38h06a4308_0
  - pooch=1.7.0=py38h06a4308_0
  - pretrainedmodels=0.7.4=pyhd8ed1ab_2
  - pulseaudio=16.1=ha8d29e2_1
  - py-mxnet=1.9.1=py38h4f77008_0
  - py-opencv=4.6.0=py38h7f3c49e_3
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=24.2.1=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h955ad1f_4
  - python_abi=3.8=2_cp38
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-metric-learning=2.7.0=pyhf063d14_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h5eee18b_0
  - qt-main=5.15.6=hf6cd601_5
  - readline=8.1.2=h0f457ee_0
  - safetensors=0.4.5=py38ha89cbab_0
  - scikit-learn=1.3.2=py38ha25d942_2
  - setuptools=65.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - svt-av1=1.4.1=hcb278e6_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - timm=1.0.11=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - torchmetrics=1.5.2=pyhe5570ce_0
  - ttach=0.0.3=pyhd8ed1ab_0
  - typing-extensions=4.9.0=py38h06a4308_1
  - typing_extensions=4.9.0=py38h06a4308_1
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=1.26.13=py38h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - bcrypt==4.3.0
      - boto3==1.37.11
      - botocore==1.37.11
      - cachetools==5.5.2
      - captum==0.7.0
      - certifi==2025.1.31
      - charset-normalizer==2.0.12
      - click==8.1.8
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - dnnlib==0.0.1
      - fire==0.7.0
      - flatbuffers==25.9.23
      - frozenlist==1.5.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - graphviz==0.8.4
      - grpcio==1.70.0
      - huggingface-hub==0.26.3
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jmespath==1.0.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - legacy==0.1.7
      - lightning-lite==1.8.0
      - lightning-utilities==0.11.9
      - lmdb==1.6.2
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.4.2
      - megfile==3.1.7
      - modelscope==1.31.0
      - multidict==6.1.0
      - mxnet==1.9.1
      - ninja==1.11.1.3
      - numpy==1.22.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.3.dev33+g93da21e
      - oauthlib==3.2.2
      - onnxruntime==1.19.2
      - opencv-python==4.10.0.84
      - packaging==24.2
      - pandas==2.0.3
      - paramiko==3.5.1
      - pillow==10.4.0
      - pip==25.0.1
      - propcache==0.2.0
      - protobuf==5.29.1
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pynacl==1.5.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.8.6
      - pytz==2025.2
      - pywavelets==1.4.1
      - regex==2024.11.6
      - requests==2.26.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - s3transfer==0.11.4
      - scikit-image==0.21.0
      - scipy==1.10.1
      - svgwrite==1.4.3
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - tifffile==2023.7.10
      - tokenizers==0.20.3
      - torch==1.13.1+cu117
      - torch-fidelity==0.3.0
      - torchaudio==0.13.1
      - torchvision==0.14.1+cu117
      - tqdm==4.67.1
      - transformers==4.46.3
      - tree==0.2.4
      - triton==3.0.0
      - tzdata==2025.2
      - werkzeug==3.0.6
      - yarl==1.15.2
      - zipp==3.20.2
